<?php $footer_about_us = $block -> getLayout() -> createBlock('Magento\Cms\Block\Block')-> setBlockId('footer_about_us')-> toHtml(); ?>
<?php if ($footer_about_us): ?>
  <?= $footer_about_us; ?>
<?php else: ?>
  <div class="footer-about-us">
      <div class="footer-logo"><a class="brand" href="<?= $block->getUrl() ?>"><img class="brand-logo" src="<?= $block->getViewFileUrl('images') . '/rctv.png'; ?>" alt="Rare Collectibles TV" /></a></div>
      <div class="about-us">At Rare Collectibles TV, we offer the finest in rare conis, US coins and currency, gold, silver, art, and collectibles. <br /> We Value our customers and want you to be completely satisfied. RCTV offers a 30-day money back guarantee on everything we sell</div>
  </div>
<?php endif; ?>