<?php $footer_links = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links')->toHtml(); ?>
<?php if ($footer_links) : ?>
    <?= $footer_links; ?>
<?php else : ?>
    <div class="footer-widgets">
        <div class="column">
            <header>Contact us Monday - Friday 10AM - 5PM</header>
            <div>
                <section class="footer-info">
                    <article>
                        <span class="header">Phone</span>
                        800-581-7273
                    </article>
                    <article>
                        <span class="header">Social</span>
                        <article class="social-icons">
                            <li><a class="social-icon" href="https://www.instagram.com/rarecollectiblestv/" target="_blank"><span class="fab fa-instagram"><em></em></span></a></li>
                            <li><a class="social-icon" href="https://www.facebook.com/rarecollectiblestv/" target="_blank"><span class="fab fa-facebook"><em></em></span></a></li>
                            <li><a class="social-icon" href="https://www.youtube.com/channel/UC9jW6L6_S6C5IYC_lvISg6Q" target="_blank"><span class="fab fa-youtube"><em></em></span></a></li>
                        </article>
                    </article>
                </section>
                <section class="footer-info">
                    <article>
                        <span class="header">Email</span>
                        info@rarecollectiblestv.com
                    </article>
                    <article class="address">
                        <span class="header">Address</span>
                        Rare Collectibles TV, LLC <br /> 21213-B Hawthorne Blvd, #344 Torrance, California 90503
                    </article>
                </section>
            </div>
        </div>
        <div class="column">
            <header>About RCTV</header>
            <ul class="footer-links">
                <li>Company</li>
                <li>Hosts</li>
                <li>PACT</li>
                <li>Showtimes</li>
            </ul>
        </div>
        <div class="column">
            <header>Additional Info</header>
            <ul class="footer-links">
                <li>Privacy Policy</li>
                <li>Return Policy</li>
                <li>Terms Of Use</li>
                <li>Terms Of Sale</li>
                <li>FAQ</li>
                <li>Sitemap</li>
            </ul>
        </div>
    </div>
<?php endif; ?>