<div class="section-item-content nav-sections-item-content" id="store.menu" data-role="content" role="tabpanel" aria-hidden="false">
    <nav class="navigation main-nav-items rctv-nav" data-action="navigation">
        <ul class="navigation-items">
            <li>Watch Live TV</li>
            <li>Coins</li>
            <li>Collectibles</li>
            <li>Private Advisors</li>
            <li>News</li>
            <li>Hall of Fame</li>
        </ul>
    </nav>
</div>